service: insta-serverless-clone
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: sa-east-1
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteNetworkInterface
        Resource:
          - "*"

functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
    vpc:
      securityGroupIds:
        - sg-1f902a54
      subnetIds:
        - subnet-85e9a9e3
        - subnet-4bffb902
        - subnet-3186c86a

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: true
